'use client';
import {useEffect,useRef,useState} from 'react';
import GalleryTunnel from '@/components/originkit/ui/gallery-tunnel';
import gsap from 'gsap';
const images=[{src:'/images/villa.jpg'},{src:'/images/pavilion.jpg'},{src:'/images/interior.jpg'}];
const colors=['#ed5634','#aab89a','#d7d6c8','#4e5e45'];
export default function Intro({onEnter}:{onEnter:()=>void}){const el=useRef<HTMLDivElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const busy=useRef(false);const [entering,setEntering]=useState(false);const [reduced,setReduced]=useState(false);
useEffect(()=>{setReduced(matchMedia('(prefers-reduced-motion: reduce)').matches);return()=>{if(timer.current)clearTimeout(timer.current);gsap.killTweensOf(el.current)}},[]);
function enter(){if(busy.current)return;busy.current=true;setEntering(true);const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;gsap.to('.intro-progress',{width:'100%',duration:2,ease:'none'});if(!reduce){gsap.to('.intro-center',{opacity:0,y:-30,duration:.6});gsap.to('.tunnel-mount',{scale:1.35,duration:2,ease:'power2.in'});gsap.to(el.current,{opacity:0,duration:.55,delay:1.45})}timer.current=setTimeout(onEnter,2000)}
return <div className="intro" ref={el}><div className="intro-top"><a className="brand" href="#home" onClick={e=>{e.preventDefault();enter()}}>FORMA<span>®</span></a><span>ARCHITECTURE, IN A NEW DIMENSION.</span></div><div className="tunnel-mount"><GalleryTunnel images={images} colors={colors} background="#1c201a" lineColor="#9aa18b" lineOpacity={18} grid={3} speed={reduced?0:entering?220:18} boost={20} label={false} fade={70} style={{width:'100%',height:'100%'}}/></div><div className="intro-center"><span className="eyebrow">A JOURNEY FROM PARTS TO PLACES</span><h2>Step into<br/><em>something new.</em></h2><button className="enter-button" onClick={enter} disabled={entering}>{entering?'Entering…':'Enter the studio'}<span>↗</span></button></div><div className="intro-bottom"><span>SPACES, ASSEMBLED.</span><span aria-live="polite">{entering?'YOUR JOURNEY BEGINS…':'CLICK TO BEGIN THE EXPERIENCE'}</span><span>© FORMA 2026</span></div><div className="intro-progress"/></div>}
