'use client';
import {useEffect,useRef,useState} from 'react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import House from './house';
import Intro from './intro';
const works=[{title:'The Courtyard House',type:'RESIDENTIAL / 2026',image:'/images/villa.jpg',desc:'A quiet retreat, framed around an open sky.'},{title:'Between the Trees',type:'RETREAT / 2025',image:'/images/pavilion.jpg',desc:'Light on the land. Connected to its surroundings.'},{title:'Room to Breathe',type:'INTERIOR / 2026',image:'/images/interior.jpg',desc:'Natural materials. Space for everyday rituals.'}];
export default function Page(){const [entered,setEntered]=useState(false);const [explode,setExplode]=useState(false);const [replay,setReplay]=useState(0);const root=useRef<HTMLDivElement>(null);
useEffect(()=>{gsap.registerPlugin(ScrollTrigger);if(!entered)return;const ctx=gsap.context(()=>{gsap.from('.hero-line span',{yPercent:115,duration:1.25,stagger:.12,ease:'power4.out'});gsap.from('.hero-meta',{opacity:0,y:20,delay:.7,duration:1});gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>{gsap.from(el,{y:65,opacity:0,duration:1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 89%'}})});},root);return()=>ctx.revert()},[entered]);
useEffect(()=>{document.body.style.overflow=entered?'':'hidden';return()=>{document.body.style.overflow=''}},[entered]);
return <div ref={root}>{!entered&&<Intro onEnter={()=>setEntered(true)}/>}
<main aria-hidden={!entered} inert={!entered}>
<header><a className="brand" href="#home">FORMA<span>®</span></a><nav><a href="#work">Selected work <sup>03</sup></a><a href="#studio">The studio</a><a href="#process">Our process</a></nav><a className="contact-link" href="#contact">Let’s build together <span>↗</span></a></header>
<section id="home" className="hero"><div className="eyebrow hero-meta"><span className="square"/> INDEPENDENT ARCHITECTURE STUDIO <span className="edition">EST. 2026 — VIETNAM</span></div><h1><div className="hero-line"><span>Good spaces.</span></div><div className="hero-line"><span>Built <em>together.</em></span></div></h1><div className="hero-stage"><div className="stage-note hero-meta"><span>01 / THE ASSEMBLY</span><p>Considered in parts.<br/>Extraordinary as a whole.</p></div><House active={entered} exploded={explode} replay={replay}/><div className="stage-caption"><span>FIG. 01 — THE GARDEN RESIDENCE</span><div><button onClick={()=>setExplode(!explode)}>{explode?'− Assemble':'＋ Explore the layers'}</button><button aria-label="Replay house assembly and car arrival" onClick={()=>{setExplode(false);setReplay(r=>r+1)}}>↻</button></div></div></div><div className="hero-bottom hero-meta"><p>Architecture is more than a place.<br/>It’s how everything comes together.</p><a className="round-link" href="#work">Explore our work <span>↓</span></a><span className="coordinates">16.0544° N<br/>108.2022° E</span></div></section>
<div className="ticker" aria-hidden="true"><div>THOUGHTFULLY DESIGNED <b>✳</b> BEAUTIFULLY ASSEMBLED <b>✳</b> MADE FOR LIVING <b>✳</b> THOUGHTFULLY DESIGNED <b>✳</b> BEAUTIFULLY ASSEMBLED <b>✳</b></div></div>
<section className="work section" id="work"><div className="section-head reveal"><span className="eyebrow">01 / SELECTED WORK</span><h2>Different places.<br/>One considered approach.</h2><span className="small-muted">A COLLECTION OF SPACES<br/>FOR THE WAY WE LIVE.</span></div><div className="projects">{works.map((w,i)=><article className={'project reveal project-'+i} key={w.title}><a href="#contact" className="project-image"><img src={w.image} alt={w.title} loading="lazy"/><span className="project-number">0{i+1}</span><span className="project-arrow">↗</span></a><div className="project-info"><h3>{w.title}</h3><span>{w.type}</span></div><p>{w.desc}</p></article>)}</div></section>
<section id="studio" className="studio section"><span className="eyebrow reveal">02 / OUR PHILOSOPHY</span><div className="studio-content"><h2 className="reveal">Less noise.<br/>More <em>meaning.</em></h2><div className="reveal"><p className="large-copy">We believe the best spaces don’t demand your attention. They make room for your life.</p><p>At FORMA, we bring architecture, interiors and modular thinking into one conversation. Every connection is intentional. Every material has a purpose. Every detail belongs to the whole.</p><a className="text-link" href="#process">Discover how we work <span>↗</span></a></div></div><div className="principles reveal"><div><span>01</span><h3>Honest materials</h3><p>Concrete, timber, glass. Beautiful in their own right.</p></div><div><span>02</span><h3>Human proportions</h3><p>Spaces shaped around the rhythms of real life.</p></div><div><span>03</span><h3>Lasting connections</h3><p>Parts that work together. Places that grow with you.</p></div></div></section>
<section id="process" className="process section"><div className="section-head reveal"><span className="eyebrow">03 / FROM IDEA TO FORM</span><h2>Good things come<br/>together. Step by step.</h2></div><div className="steps">{[['Listen','It starts with you. Your routines, your ambitions, your idea of home.'],['Explore','Sketches become possibilities. We test light, material and proportion together.'],['Assemble','Every piece finds its place. An idea becomes a space you can step inside.']].map(([title,copy],i)=><div className="step reveal" key={title}><span className="step-no">0{i+1}</span><h3>{title}<span>↗</span></h3><p>{copy}</p></div>)}</div></section>
<section id="contact" className="contact section"><span className="eyebrow reveal">HAVE SOMETHING IN MIND?</span><a className="contact-title reveal" href="mailto:hello@forma.studio">Let’s make<br/><em>room for it.</em><span>↗</span></a><div className="contact-bottom"><p>A home. A place. A new possibility.<br/>Every great space starts with a conversation.</p><a href="mailto:hello@forma.studio">hello@forma.studio ↗</a></div></section>
<footer><a className="brand" href="#home">FORMA<span>®</span></a><span>SPACES, ASSEMBLED.</span><span>© 2026 FORMA STUDIO · CONCEPT WEBSITE</span><button onClick={()=>{window.scrollTo(0,0);setEntered(false)}}>Replay experience ↗</button></footer>
</main></div>}
